- name: Deploy UPI cluster
  import_tasks: deploy_cluster_upi.yml
  when: ocp4_aio_deploy_type == 'upi'

- name: Deploy IPI cluster
  import_tasks: deploy_cluster_ipi.yml
  when: ocp4_aio_deploy_type == 'ipi'

- name: deploy SNO cluster
  import_tasks: deploy_cluster_sno_iso.yml
  when: ocp4_aio_deploy_type == 'sno'
